import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import AuthProvider from "@/context/AuthProvider";
import { Toaster } from "@/components/ui/sonner"
import AdminHeader from "@/components/AdminHeader";
import AdminNavbar from "@/components/AdminNavbar";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <AuthProvider>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <div className="flex min-h-screen">
            <AdminNavbar />
            <div className="flex-1 flex flex-col">
              <AdminHeader />
              <main className="flex-1 p-4">{children}</main>
              <Toaster />
            </div>
          </div>
        </body>
      </AuthProvider>
    </html>
  );
}
